### ISSUE TITLE
Messages should be deleted in new Message module

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#11]
We now save emails and private messages in the message module. We should add a delete function in the main list so users are able to delete unnecessary mails.

**Comment by sirnone** [comment]
Hello Fasse,

the delete on Emails should be easy, but on PM's I think it will be complicated
because on PM's we would delete full conversations on both users (sender and receiver)

what do you think about a "delete request" in this case? -> if one user want to delete the conversation, the other get an "accept" and "denied" on the possition of the delete button and the message is blocked until he make a decission? we can in this case also think about an "revert"-button on the requester site.

**Comment by Fasse** [comment]
For this version I would make it simple. Only delete emails and maybe delete the whole conversation if one of the participiants deletes it. Maybe later we could think about a more complex solution.

**Comment by sirnone** [comment]
Hello Fasse,
I had some more time today after work... so now i implement the big solution and solve some little bugs in emailing and chat. can you please test and give a short feedback?

**Comment by sirnone** [comment]
feedback from Fasse was OK -> improvements in code will be done in other way.
