### ISSUE TITLE
Possible to allow registrations without requiring username or password. 

### ISSUE THREAD

**Issue by GForce2010** [Admidio/admidio#1237]
Our members club want to use Admidio for our membership database, primarily for administration.

We would like prospective members to be able to register themselves but we will have no requirement to allow users to be able to login again after the initial registration. So is it possible to remove the Username and Password fields from the registration form? 

We are just trying to remove any possibility of confusion for members by not having them require a separate login account just for this as well as Discourse.

Thanks.

Fraser.

**Comment by Fasse** [comment]
We will not implement such a feature because I don't understand the use. You can disable registration. But if you enable it, you also have the possibility to login. There you can remove a lot a features and rights for the users so they could do not much. But to disable the login feature is not the way we want Admidio to work.
