### ISSUE TITLE
New role setting to control the visibility of role memberships

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#1245]
Until now you can only control the visibility of a role and implicit allow the users to view the profile of the role members if they could view the role membership.

We should add a new checkbox to the role configuration dialog **View profile of role members**. 
This checkbox should be set by default if you create a new role.
This checkbox must be set within the update to all existing roles, so the existing behavior will not be changed.

if the checkbox is unchecked but the preference to view the role membership is set than users could view role lists but could only see first name and last name of the members. It's not allowed to view the profile of any member.

**Comment by idnovic** [comment]
This would solve an issue that I have. 
I do not want to leak the login name because our users use their email as login name. 

As far as I understand this suggestion, after this is implemented the login name should no longer be viewable. 

We have an other field of typ number (room number). 
We would prefer that this field stays visible. 

Would it be possible to implement this feature in such way that more profile fields can be set as still viewable?

Maybe add an option to the profile fields editor that allows us to set which fields are still viewable.

**Comment by idnovic** [comment]
Or do I misunderstand this and instead the profile page of an other user can not be visited at all?

**Comment by Fasse** [comment]
Yes you misunderstand this issue. With this preference you are not allowed to view the profile. Your are only allowed to view a role membership and can therefore view the first name and last name of the user.

**Comment by idnovic** [comment]
But users are still able to view entries in lists?
If I create a list and add the room number to this list, the room number is still visible in the list but the user is not allowed to visit the profile page of an other user, right?

**Comment by Fasse** [comment]
He is not allowed to view the Profile and he is not allowed to view any other profile fields in a list e.g. room number. This preference should only show others or the User himself who is member of that group.

**Comment by Fasse** [comment]
@idnovic  The title of this issue was missleading. I changed it :-)
