### ISSUE TITLE
set hashcost preference by benchmark

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#125]
#112 

This is to set the optimal cost value for the hash function.
a smaller cost value is faster but less secure
a higher cost value is slower but more secure

the optimal cost value is, if the time for the hash function is between 0,2 and 0,5 sec. This benchmark calc the highest cost value which max takes 0,5sec to hash. This is needed because every server has an other performance and everyone should use the higherst cost for his server that didn't leed in performance problems

**Comment by Fasse** [comment]
@ximex  I got the following error after start the update from version 3.0 to 3.1:
> Parse error: syntax error, unexpected '[' in /Users/Jennifer/Sites/github/admidio/adm_program/installation/update.php on line 324

Line 324 ist:
> $orga_preferences['system_hashing_cost'] = end($benchmarkResults)['cost'];

Same problem could be in installation.php line 645

**Comment by ximex** [comment]
could you try if this works:
```php
$orga_preferences['system_hashing_cost'] = (end($benchmarkResults))['cost'];
// OR
$orga_preferences['system_hashing_cost'] = $benchmarkResults[count($benchmarkResults)]['cost'];
// OR
$result = end($benchmarkResults);
$orga_preferences['system_hashing_cost'] = $result['cost'];
```

**Comment by Fasse** [comment]
I changed the return array. We don't need all tested costs. Only the best tested cost with time is needed.

**Comment by ximex** [comment]
:+1:

**Comment by Fasse** [comment]
We must remove this hashcost determination :(
If the cost value changed through update, than you are not able to verify old password hashes with another cost paramter.

In my case I write the demo_data to database. Then I do the update to 3.1 therefore I need my password and my password will be rehashed to our new library passwort_compat. At this point the default hast cost will be used. Within the update the new cost is determinated and within my next login after update the login still fails because it could not get the right hash.

**Comment by ximex** [comment]
ok will look on it today. but i think this is another problem.
`if(PasswordHashing::verify($password, $currHash))` user.php L 279
the cost value to verify is extracted out of the $currHash.

**Comment by Fasse** [comment]
Ok, maybe my last checkin is the problem where I check `isset($gPreferences['system_hashing_cost'])`
But if I don't check we got a syntax error because before the update to 3.1 we don't know this parameter and to update I need to login where Admidio wants to rehash. There we need a default cost if Pref is not defined.

**Comment by ximex** [comment]
Ok than mybe something like that?
```php
if($doHashing)
{
    // get the saved cost value that fits your server performance best and rehash your password
    $cost = 10;
    if (isset($gPreferences['system_hashing_cost']))
    {
        $cost = intval($gPreferences['system_hashing_cost']);
    }
    $newPassword = PasswordHashing::hash($newPassword, PASSWORD_DEFAULT, array('cost' => $cost));
}
```

**Comment by Fasse** [comment]
ok, now it works :)

**Comment by ximex** [comment]
one more fix. you set 10 as constant and not the $cost variable
0b7f49a182d317d1b95a600e41b76f92b7710268

**Comment by Fasse** [comment]
oh sorry, that was a quick fix so I could work with Admidio. Forgot to change it back after I do the patch :/
