### ISSUE TITLE
Docker build outdated

### ISSUE THREAD

**Issue by idnovic** [Admidio/admidio#1366]
Greetings,

I am moving our admidio instance from a VM to docker. 

The problem is that I already updated to the latest admidio version of 4.2.2 before the database export. 

I can not restore admidio because the docker version is out of date. 

@schast please update the docker version if you find time. Thank you and sorry for the ping.

**Comment by sielnet** [comment]
Also please allow the following use case:

startup.sh is missing adm_program. If a bind mount for the adm_program folder is set it should be used instead of the internal adm_program folder inside the container. This is useful for setups with patched files in adm_program.
```
# check for existing admidio directories in docker volumes
for dir in "adm_plugins" "adm_themes" "adm_my_files" ; do
```

That way most users can update admidio with the build tag. And users with a special use case can still use a version with patched system files.

Example for an update from 4.2.1 to 4.2.2:

most users:
container v4.2.1 gets replaced with v4.2.2.
admidio is updated.
done

users with patched system files:
container v4.2.1 is running with a mount set for adm_program because of edited files.
container is stopped.
container is replaced with v.4.2.2 but the mount for adm_program is not set.
admidio is updated using the internal container version of adm_program.
container is stopped.
user manually updates files in the external location of adm_program as needed with the new v4.2.2.
container is replaced with mount set for the edited version of adm_program.

This seems complicated but it has the advantage that the update process is done with the official admidio version.
After the update the user creates the edited/patched version and mounts it.

This allows for save updates and patched versions altogether.
I hope that makes sense. I

**Comment by schast** [comment]
v4.2.2 has been released.
I will make some improvements to the update process before I set the latest tag to v4.2.2.
