### ISSUE TITLE
Event always show message participation not possible

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#1410]
If an event is not configured for participation the message "participation not possible" will still be shown.

**Comment by antihero05** [comment]
@Fasse: It seems this fix does not solve the problem completely as it does not show the status button for events in the past because $buttonClass and $buttonText are empty in that case:

`        } elseif ($date->deadlineExceeded() || $outputNumberMembers >= (int) $date->getValue('dat_max_members')) {
            // Show warning for member of the date role if deadline is exceeded and now no changes are possible anymore
            if ($participants->isMemberOfEvent($gCurrentUserId)) {
                if ($getView !== 'detail') {
                    $outputButtonParticipation = '<span class="' . $buttonClass . '">' . $iconParticipationStatus . '</span>';
                }
                $attentionDeadline = '
                        <div class="alert alert-info" role="alert">
                            <span class="'.$buttonClass.'">' . $iconParticipationStatus . ' ' . $buttonText . '</span>`

Besides that these buttons are missing as well:
-Link to participants list
-Link to send email to participants
-Link for managing new participants => Don't know if it is intended by design but I would highly prefer if a leader of an event still has the possibility to add/remove users after the deadline

**Comment by Fasse** [comment]
@antihero05 This issue should not fix the problem you described here. Your problem is fixed with #1413
