### ISSUE TITLE
Tentative status for useres in events

### ISSUE THREAD

**Issue by silverches** [Admidio/admidio#197]
Hello,

Is it maybe possible to add diffirent statusses on events?

I would like to get the statuses like 'not available' and 'tentative'. 
##

**Comment by thomas-rcv** [comment]
There is a thread in our Forum about this Feature Request:

http://www.admidio.org/forum/viewtopic.php?f=2&t=3873&hilit=unsicher

Regarding the logic function it should be possible to have a third Parameter "tentative" to be set by the users, or if a member or user is assigned to an event it should automatically set tentative until :  

1. User confirm the state
2. User Change the state for this date.

Therfor we should define a timestamp set if the user called the Event participation.

I will Change this issue to a Feature Request.
I already defined the datafield columns for this issue since starting Versinon 3.0

**Comment by silverches** [comment]
Sorry i didn't see that thread. 
Well personally i would say that if a member gets assigned to a event, they would get the assigned status, till the member confirms or changes state. 

Then you can be sure that that person saw the event.

**Comment by thomas-rcv** [comment]
Generally you are right.
I´m thinking a little bit more functionally.
In my opinon we should think about a further state  for participations: Not sure (tentative) with new Icon. Assiging a member to an event it would be logical correct, because the assignee do not know the facts at this time until the member confirm.
Therfor I would log the state of the user in database with a flag , after reading in module or calling a participation form.
