### ISSUE TITLE
Implement date range filter in lists

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#203]
It should be possible to look for roles in the past and also in the future.
We could use the date range filter like we have in the date module.

See forum:

http://www.admidio.org/forum/viewtopic.php?f=2&t=6692&p=22683#p22683

**Comment by Fasse** [comment]
I had a look to your implementation. The function works as expected but I'm not very happy with the user interface. Within the lists list you don't know what the dates for. Nothing changed if you changed the dates. 
Maybe it's better to place them within the lists presentation and with a better field description so that a user know what changed. Within the event module this was no problem because you know which dates you can filter but here it's a problem. Also with the implementation now you get conflicts with the member status field of mylist. If we have it within the show-list than maybe we can remove the member status field of mylist.
It would also be nice if the filter will only be shown if the role has former or future members.

**Comment by thomas-rcv** [comment]
You are definetly right.
At this time there a several things to do before we could pull it. For example the values of the dates are not set immediatly. Within  the first commit you have to change the category once to get the new date range. I need to add a little bit of javascript for it. 
I didn't tried the behaviour of my lists so far but it doesn't sound good if we already have trouble shooting there. Generally the implementation as I Understood the thread is to have it in list module. My Lists is for my understanding an own module. Sure, both provides list with recordsets at the end but in mylist we have a lot of additional options wirh member states and condition fields.
So if possible I didn't plan to change anything in mylists. Of course if new issues are coming up while the implemantation regarding functional stuff we can discuss and define a strategy how to work on

**Comment by thomas-rcv** [comment]
Please have a look again.
I moved the filter to list_show and also added a text phrase for it. -> we can discuss
I also needed to store some values in the session, using the form.
Some logical improvements and session handling for the variables must be done at this time.
Generelly it should work now, except for minor changes.
