### ISSUE TITLE
Wrong passwort on initial registration

### ISSUE THREAD

**Issue by martinbrylski** [Admidio/admidio#294]
Given:
Admidio 3.0.6.
A profile P1 for user U1 is already stored in the system (with full name F1 and an email E1).

When:
U1 registers in admidio with his full name F1, but another email E2.
And the user was unlocked by the admidio webmaster, automatically assigning U1 to the suggested profile P1.

Then:
The user cant log in with his chosen credentials, getting a "password/username does not match" error.

**Comment by Fasse** [comment]
Could you try this behavior with our 3.1 beta?

**Comment by martinbrylski** [comment]
In 3.1beta I'am not able to unlock the user: "Dieser Benutzer besitzt schon ein gültiges Login."
See http://spielwiese.admidio.org/adm_program/modules/registration/registration_assign.php?new_user_id=357

Used the same procedure as above.

**Comment by Fasse** [comment]
Sorry @martinbrylski , through the beta phase I forgot your issue :(

The problem of your last comment was fixed here:
https://github.com/Admidio/admidio/issues/304

The problem with the invalid login was fixed with the commit in this issue.

But both have nothing to do with the email address. Within my tests I always used a different email address and got no error.

**Comment by Fasse** [comment]
The bug described at the initial comment was fixed.
