### ISSUE TITLE
Menu should be configurable and saved in database

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#339]
The Admidio main menu should be saved in database and should also be configurable. Therefore a simple script which show the menu structure should be created and a small dialog to edit each entry.

The following columns should the new table **adm_menu** should contain:
- mnu_id     (main id of the table
- mnu_mnu_id_parent (the node to which the actual link belong)
- mnu_node (true if the actual entry is not a link but a node)
- mnu_url (url to the script that should be called)
- mnu_text (text of the link)
- mnu_icon (icon of the link)
- mnu_description (optional a description to the link can be stored)

**Comment by Fasse** [comment]
http://forum.admidio.org/viewtopic.php?f=7&t=6807

**Comment by sirnone** [comment]
we should but 3 additonal bool fields in the tabel:

show in main menu
show in mobile menu
show in left site (index.php)

**Comment by ximex** [comment]
@sirnone status?

**Comment by sirnone** [comment]
main functions are working. Now I need to check the code again and fix some small code problems.
if someone has time, than you can make a first test and give some feedback.

we should also check the install and Update process, because this is a big change in the system that can break many things.
we should also check, if we need a special update instruction because of this new feature.
