### ISSUE TITLE
Integrate new Captcha library

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#66]
https://github.com/dapphp/securimage

http://admidio.org/forum/viewtopic.php?f=13&t=6397

**Comment by Fasse** [comment]
We should implement a new captcha library that supports various captcha methods and a easy customizing.

**Comment by silverches** [comment]
I'm not sure about how well it withhold bots, maybe add recaptcha2 of google? https://www.google.com/recaptcha/intro/index.html

**Comment by ximex** [comment]
@silverches i like recaptcha2 too.
only problem: little tracking by google

**Comment by Silicon1602** [comment]
@ximex @silverches That's true, but imho it isn't that much tracking, since the recaptcha2 will only appear at the registration. I have chosen Admidio, because I didn't want to use Facebook/Google+ for our association anymore, but in my opinion there are much more advantages than disadvantages (==> tracking).
