### ISSUE TITLE
Copy already sent messages

### ISSUE THREAD

**Issue by udobes** [Admidio/admidio#738]
Beim versenden von Nachrichten kommt es vor, dass man was vergessen hat und die Nachricht gerne ergänzen würde. Sei es mit ergänzendem Text oder einem Anhang, den man vergaß anzuhängen. 
Es wäre wünschenswert, wenn es im Nachrichtenjournal einen 'Ergänzen'-Button gäbe, der die Möglichkeit gibt, der Nachricht zusätzliche Infos oder Anhang anzuhängen und dies dann an den gleichen Verteiler (der gemäß dem Namen der Gruppe neu gefiltert wird) geschickt wird. 
Gruß Udo

**Comment by Fasse** [comment]
Please use english at GitHub, because our development should be english only. Otherwise the german forum would be a place for proposals.

As I read your headline you suggest two different ways for messages. One way will be to duplicate a message and than expand the message text and send this message. Another way will be only to expand the message and don't send it.

I would prefer the first way. Implement a method to duplicate/copy a message. Is that the way you also think about?

**Comment by udobes** [comment]
Yes. If you sent out a message and things are changing or you have to add
some information or attachments, then we should be able to copy the message
and the receipients to send an additional mail.

In circumstances when the first message was sent long time ago, it would be
premium functionality, when the receipients where newly filtered depending
to their groups.

Thanks so far
Udo

-----------------------------------------<°///><
udo@besenreuther.de
72535 Heroldstatt-Sontheim
---------------------------------------------------

2018-04-17 22:44 GMT+02:00 Markus Faßbender <notifications@github.com>:
