### ISSUE TITLE
Installation stuck at creating database

### ISSUE THREAD

**Issue by frankhubrepo** [Admidio/admidio#976]
I tried both the beta and the official version in my localhost, and both times I haven't gotten past the "creating database" screen:
![image](https://user-images.githubusercontent.com/26232103/103901674-d52ed280-50cf-11eb-8526-fc7b2f52559d.png)

Has anyone ran into this issue?

**Comment by Fasse** [comment]
Do you have any entries in the PHP errorlog?

**Comment by Fasse** [comment]
We need more informations about this issue. Do you have access to PHP logfiles?

**Comment by zhuguangxx** [comment]
我遇到的问题是一样的，卡在安装数据库页面。安装环境：php56，mysql5.7.33.
php慢日志：[21-Feb-2021 01:22:52] NOTICE: child 470828 stopped for tracing
[21-Feb-2021 01:22:52] NOTICE: about to trace 470828
[21-Feb-2021 01:22:52] NOTICE: finished trace of 470828
The problem I encountered was the same, the card was in the install database page. Installation environment: php56, mysql5.7.33

PHP slow log: [21-feb-2021 01:22:52] Note: child 470828 stopped for tracing

[21-Feb-2021 01:22:52] NOTICE: about to trace 470828

[21-Feb-2021 01:22:52] NOTICE: finished trace of 470828

**Comment by zhuguangxx** [comment]
The problem I encountered was the same, the card was in the install database page. Installation environment: php56, mysql5.7.33
PHP slow log: [21-feb-2021 01:22:52] Note: child 470828 stopped for tracing
[21-Feb-2021 01:22:52] NOTICE: about to trace 470828
[21-Feb-2021 01:22:52] NOTICE: finished trace of 470828

**Comment by zhuguangxx** [comment]
[21-Feb-2021 01:06:27] NOTICE: fpm is running, pid 496760
[21-Feb-2021 01:06:27] NOTICE: ready to handle connections
[21-Feb-2021 01:06:28] NOTICE: fpm is running, pid 496778
[21-Feb-2021 01:06:28] NOTICE: ready to handle connections
[21-Feb-2021 02:00:01] NOTICE: Reloading in progress ...
[21-Feb-2021 02:00:01] NOTICE: reloading: execvp("/www/server/php/56/sbin/php-fpm", {"/www/server/php/56/sbin/php-fpm", "--daemonize", "--fpm-config", "/www/server/php/56/etc/php-fpm.conf", "--pid", "/www/server/php/56/var/run/php-fpm.pid"})
[21-Feb-2021 02:00:01] NOTICE: using inherited socket fd=10, "/tmp/php-cgi-56.sock"
[21-Feb-2021 02:00:01] NOTICE: using inherited socket fd=10, "/tmp/php-cgi-56.sock"
[21-Feb-2021 02:00:01] NOTICE: fpm is running, pid 502089
[21-Feb-2021 02:00:01] NOTICE: ready to handle connections

**Comment by Fasse** [comment]
do you have any new tables of Admidio in the database after that? Or is the database still empty?

**Comment by zhuguangxx** [comment]
> do you have any new tables of Admidio in the database after that? Or is the database still empty?

no ,there is no tables.

**Comment by mrlawrencelam** [comment]
I have the same issue. Installation stuck at "Creating Database.....". No table created under phpMyAdmin.

This is taken from the error log:

 PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/Database.php:463
Stack trace:
#0 /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/Database.php(389): Database->loadTableColumnsProperties('adm_sessions')
#1 /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/TableAccess.php(141): Database->getTableColumnsProperties('adm_sessions')
#2 /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/TableAccess.php(100): TableAccess->clear()
#3 /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/Session.php(59): TableAccess->__construct(Object(Database), 'adm_sessions', 'ses')
#4 /home/rljjnww/public_html/upoint_membership/adm_program/system/common.php(97): Session->__construct(Object(Database), 'afc68aeff73c821...', 'ADMIDIO_KLTGA_u...')
#5 /home/rljjnww/public_html/upoint_membership/index.php(27): require_once('/home/rl8klsljj in /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/Database.php on line 463

**Comment by Fasse** [comment]
> #5 /home/rljjnww/public_html/upoint_membership/index.php(27): require_once('/home/rl8klsljj in /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/Database.php on line 463

Hmm, the errorlog looks strange because it started with index.php at the main folder. There should be an errorlog that will start at **/home/rljjnww/public_html/upoint_membership/adm_program/installation** ... 

Is there something within the logs?

**Comment by mrlawrencelam** [comment]
I found the problem.

When I first installing, I used MS-Edge browser. After submitting the online setup form, I got a message saying the password which I chose was not strong enough. I guess there is something wrong with the cache here. I tried re-installing a few times (clean new installation) and it always stuck at CREATING DATABASE. Cleaning the cookies and reopening Edge did not solve the problem.

I then changed to FireFox and installed again. There was no problem and the installation was complete.

**Comment by mrlawrencelam** [comment]
> > #5 /home/rljjnww/public_html/upoint_membership/index.php(27): require_once('/home/rl8klsljj in /home/rljjnww/public_html/upoint_membership/adm_program/system/classes/Database.php on line 463
> 
> Hmm, the errorlog looks strange because it started with index.php at the main folder. There should be an errorlog that will start at **/home/rljjnww/public_html/upoint_membership/adm_program/installation** ...
> 
> Is there something within the logs?

Yes, there is only one line in the log file. It says my password was not strong enough although I have carried out re-installation and used a strong password.

**Comment by Fasse** [comment]
@frankhubrepo Do you still have the problem at installation?

**Comment by esotericxa** [comment]
A great project, many extremely well done parts.
However, using Firefox to get around this problem;
is NOT a solution. It is a work around. NOT the same thing at all.
Seems to get stuck on IE11 and Brave as well.
Happy to help with documentation and to reduce gaps in install instructions for example,
but not directly skilled in PHP, XML and MYSQL for example.
Quite experienced at role based security design, so I will be interested in your model,
if I can ever get to see it.

**Comment by esotericxa** [comment]
Adding some logs
[access.log](https://github.com/Admidio/admidio/files/8210692/access.log)
[error.log](https://github.com/Admidio/admidio/files/8210693/error.log)

**Comment by esotericxa** [comment]
As in, it did not work with firefox either.
I was thinking of using this for our car club, but things are not looking good.

**Comment by esotericxa** [comment]
[PHP_Error_Admidio_Install.txt](https://github.com/Admidio/admidio/files/8210816/PHP_Error_Admidio_Install.txt)
line 443 in on of the two? files named database.php gets an error...??

**Comment by esotericxa** [comment]
Actually, it did appear to install once, after a LONG wait using Edge, so I got to logo and have a look around.
Is this project still going??

**Comment by Fasse** [comment]
@esotericxa Thanks for the logs. I will have a look at it within the next days.

**Comment by esotericxa** [comment]
Thanks Markus,

Nice little application and it is getting harder to find one that you can run on your own site.

I did not seen any errors. even when it stopped responding.

I was asked for a user id, none suggested in the install instructions,

??????

so I used root which I have used in the dim dark Linux past,

and which also appeared in a google search,

and I think the password it accepted was mysql, (also googled...????)

I could re install the thing and do screen shots of each steps

I also saw some where that the owner had stopped the project??

or was this perhaps just one part of it like a language translation.

In my last work on the AMP stack, I seem to remember that the data base,

has at least two logons, as in owner administrator, and then at least one client or user.
This is probably documented at the mysql home site I suppose.

The usual problem I find with the AMP stack, is that this is all considered to be

stuff that needs no explanation or documentation, because every one knows it.

I think this apparent "assumed knowledge" model is the main thing holding the AMP stack and
the linux community back.

But it is a lot of boring stuff to document for the occasional "outsider". to use.

I am retired from over 40 years in IT, mostly in IBM mainframe and eventually WINTEL
moving to application design and construction and systems architecture.

Not much work in the open source world, but I can wade through it if really required.

I just do not see the point of instructions that are missing key components..??

Happy to help with testing the install process until it works though if I can help.

 
Thanks again for the reply?
Regards.

Colin

**Comment by Fasse** [comment]
Could you have a view into your database? Has Admidio created at least one or more tables in the database?

**Comment by esotericxa** [comment]
Did a clean install

Screen printed each page.

Copied logs and other relevant files

looked at DB, look empty, screen print

By the way, it did actually install once a few days ago,

some how, and I was able to logon and look at user interface.

Thanks if you have time for this.

Colin

**Comment by esotericxa** [comment]
Ok,

more news.

I created a database within my sql called admidio1

I created a user AdmidioDBU with all privilege's and no password

Using this Db and this user, get exactly the same result.

I am truly struggling to see this as a serious offering.

**Comment by esotericxa** [comment]
And no tables are ever created

Colin

**Comment by esotericxa** [comment]
Hi. This is still an issue.
I posted this on the admidio forum a few days ago, about 60 people have looked at it and no response yet.
"
"5. In the next step you have to enter the access data to your database. These should have been provided by your hoster."

Since I am my own would be hoster, and there are no instructions about how to set up the data base;

this may be why my many install attempts have so far failed.

I can install the AMPPS but after that, it is all guessing and trial and error.

A working set of instruction would be a great helps here.

The instructions as they exist at this point, without this information, will fail,
unless there is and expert hoster to guide. I expect that this is very often the case.

sorry to lump more work on to the team but not sure what else to do.

Also, once you hit the install button, about how long should it take to get to the completion?
Running an intel Q8200S 8 gig ram, ssd for testing etc.

Also, the reference to security of 777 does not apply on Windows, this is described differently on windows
, and there may be an issue of
TPC/IP and NAMED PIPES ? adjustments in windows, that pops up occasionally?

Thanks
"
Perhaps some one could at least explain WHY these steps should be legitimately left out?
Perhaps a prerequisite for trying this out should be at least DBA beginner skills?
Thanks again

**Comment by Fasse** [comment]
I have no solution for your problem. Set up a working database is a requirement for Admidio. 

But for the next version I have implement a check at installation if the current database user has the right to create a table. Otherwise a database error will be thrown, so it's easier for all to find the problem and there will be no white page at the last installation step.

**Comment by esotericxa** [comment]
Good move. Thanks

**Comment by cybercol** [comment]
Hi,
I had the same problem as described above. Used edge and chrome but kept hanging at creating database. But solved it for me.
Two things:
Check you have no cookie blockers or adblock on the browser - I had both of these and after disabling them for my site, it created the database.
Just in case that was a fluke, just do a page refresh and see if that works - When I disabled my blockers they both did a page refresh automatically and then the database installed.
Hope that helps.

**Comment by esotericxa** [comment]
Aha, thanks.

I actually use a large host file to block stuff, so I will try removing that for my next try.

much appreciated.

If it works, I will then try and find out what the blocked link is.

I have no idea why there should be one really.

So it will be quite interesting to find out who is doing what.

Best Regards

**Comment by chelahmy** [comment]
I had the same problem with version 4.1.13. No database table was created. I'm using Chrome on localhost. Reload the page (ctrl-F5) solved the problem. Anyway, it is still a bug.

**Comment by Fasse** [comment]
Maybe your problems are solved with #1307 if you use chrome at installation.

**Comment by esotericxa** [comment]
I have voted with my feet. The response to this issue was unspeakably poor and the problem has basically never been addressed properly. Don't waste your time.

**Comment by Fasse** [comment]
@esotericxa but this is/was not only your issue and maybe someone other is still interested in a solution.
